Bootstrap: docker
From: python:3.11-slim

%labels
    MAINTAINER icaoberg, luism
    EMAIL icaoberg@psc.edu, luism@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-papis
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 0.14.1

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8

%post
    apt-get update
    apt-get install -y --no-install-recommends \
        build-essential \
        && rm -rf /var/lib/apt/lists/*
    python -m pip install --upgrade pip setuptools wheel
    pip install papis

%runscript
    papis "$@"
