Bootstrap: docker#
From: debian:latest

%labels
    MAINTAINER icaoberg, luism
    EMAIL icaoberg@psc.edu, luism@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-template 
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION version

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8

%post
    apt updatae
    apt-get -y install papis


%runscript
    papis $@"
